enableRobotsTXT: true
enableGitInfo: true
paginate: 10
summaryLength: 70

sectionPagesMenu: main

taxonomies:
  category: categories
  tag: tags
  stack: stacks

related:
  includeNewer: true
  threshold: 80
  toLower: true
  indices:
    - name: tags
      weight: 80
    - name: categories
      weight: 60
    - name: date
      weight: 10

build:
  noJSConfigInAssets: true
