enableRobotsTXT: true
enableGitInfo: true
paginate: 10
summaryLength: 70

build:
  noJSConfigInAssets: true
  writeStats: true

outputFormats:
  SearchIndex:
    mediaType: application/json
    baseName: searchindex
    isPlainText: true
    isHTML: false
    notAlternative: true

outputs:
  home:
    - HTML
    - RSS
    - SearchIndex
