# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Er"
license = "MIT"
licenselink = "https://github.com/darwin67/er/blob/master/LICENSE.md"
description = "A clean Hugo theme for blogging"
homepage = "http://github.com/darwin67/er"
tags = ["responsive", "white", "blog"]
features = ["responsive", "blog"]
min_version = "0.136.0"

[author]
  name = "Darwin Wu"
  homepage = "https://darwindwu.com"
